export const FRENCH_LOCALE = {
  everyText: 'chaque',
  emptyMonths: 'chaque mois',
  emptyMonthDays: 'chaque jour du mois',
  emptyMonthDaysShort: 'jour du mois',
  emptyWeekDays: 'chaque jour de la semaine',
  emptyWeekDaysShort: 'jour de la semaine',
  emptyHours: 'chaque heure',
  emptyMinutes: 'chaque minute',
  emptyMinutesForHourPeriod: 'chaque',
  yearOption: 'année',
  monthOption: 'mois',
  weekOption: 'semaine',
  dayOption: 'jour',
  hourOption: 'heure',
  minuteOption: 'minute',
  rebootOption: 'redémarrage',
  prefixPeriod: 'Chaque',
  prefixMonths: 'en',
  prefixMonthDays: 'le',
  prefixWeekDays: 'le',
  prefixWeekDaysForMonthAndYearPeriod: 'et',
  prefixHours: 'à',
  prefixMinutes: ':',
  prefixMinutesForHourPeriod: 'à',
  suffixMinutesForHourPeriod: 'minute(s)',
  errorInvalidCron: 'Expression cron invalide',
  clearButtonText: 'Effacer',
  // Order is important, the index will be used as value
  months: [
    'janvier',
    'février',
    'mars',
    'avril',
    'mai',
    'juin',
    'juillet',
    'août',
    'septembre',
    'octobre',
    'novembre',
    'décembre',
  ],
  // Order is important, the index will be used as value
  weekDays: [
    'dimanche',
    'lundi',
    'mardi',
    'mercredi',
    'jeudi',
    'vendredi',
    'samedi',
  ],
  // cf: https://fr.wikipedia.org/wiki/Mois#Abr%C3%A9viations
  // Order is important, the index will be used as value
  altMonths: [
    'JAN',
    'FÉV',
    'MAR',
    'AVR',
    'MAI',
    'JUN',
    'JUL',
    'AOÛ',
    'SEP',
    'OCT',
    'NOV',
    'DÉC',
  ],
  // cf: http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=3617
  // Order is important, the index will be used as value
  altWeekDays: ['DIM', 'LUN', 'MAR', 'MER', 'JEU', 'VEN', 'SAM'],
}

export const ZH_LOCALE = {
  everyText: '每',
  emptyMonths: '每月',
  emptyMonthDays: '每月的每一天',
  emptyMonthDaysShort: '日',
  emptyWeekDays: '每周的每一天',
  emptyWeekDaysShort: '星期',
  emptyHours: '每小时',
  emptyMinutes: '每分钟',
  emptyMinutesForHourPeriod: '每',
  yearOption: '年',
  monthOption: '月',
  weekOption: '周',
  dayOption: '天',
  hourOption: '小时',
  minuteOption: '分钟',
  rebootOption: '重启',
  prefixPeriod: '每',
  prefixMonths: '在',
  prefixMonthDays: '在',
  prefixWeekDays: '在',
  prefixWeekDaysForMonthAndYearPeriod: '和',
  prefixHours: '在',
  prefixMinutes: ':',
  prefixMinutesForHourPeriod: '在',
  suffixMinutesForHourPeriod: '分钟',
  errorInvalidCron: '无效的 cron 表达式',
  clearButtonText: '清除',
  weekDays: [
    '星期日',
    '星期一',
    '星期二',
    '星期三',
    '星期四',
    '星期五',
    '星期六',
  ],
  months: [
    '一月',
    '二月',
    '三月',
    '四月',
    '五月',
    '六月',
    '七月',
    '八月',
    '九月',
    '十月',
    '十一月',
    '十二月',
  ],
  altWeekDays: ['日', '一', '二', '三', '四', '五', '六'],
  altMonths: [
    '1月',
    '2月',
    '3月',
    '4月',
    '5月',
    '6月',
    '7月',
    '8月',
    '9月',
    '10月',
    '11月',
    '12月',
  ],
}

export const ENGLISH_VARIANT_LOCALE = {
  everyText: 'all',
  emptyHours: 'all hours',
  emptyWeekDays: 'all days of the week',
  emptyMonthDays: 'all days of the month',
  emptyMonths: 'all months',
  emptyMinutes: 'all minutes',
  emptyMinutesForHourPeriod: 'all',
  yearOption: 'years',
  monthOption: 'months',
  weekOption: 'weeks',
  dayOption: 'days',
  hourOption: 'hours',
  minuteOption: 'minutes',
  rebootOption: 'reboots',
  prefixPeriod: 'All',
}
export const NO_PREFIX_SUFFIX_LOCALE = {
  prefixPeriod: '',
  prefixMonths: '',
  prefixMonthDays: '',
  prefixWeekDays: '',
  prefixWeekDaysForMonthAndYearPeriod: '',
  prefixHours: '',
  prefixMinutes: '',
  prefixMinutesForHourPeriod: '',
  suffixMinutesForHourPeriod: '',
}
